config/routes.rb
Hanes::Application.routes.draw do
  root :to => "home#index"  
  devise_for :admins, :controllers => { :registrations => "admins" }
  devise_for :customers, :controllers => { :registrations => "customers" }

  scope "/manage" do
    resources :customers, :controller => :crud_customers do
      resources :orders do
        put :approve, :on => :member
        put :sent, :on => :member
        get :all_orders, :on => :collection
      end
    end
  end

  scope "/manage" do
    resources :admins do
      resources :orders do
        put :approve, :on => :member
        put :sent, :on => :member
        get :all_orders, :on => :collection
        get :to_approve, :on => :collection
      end
    end
  end

  

end

app/models/customer.rb
class Customer < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :token_authenticatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me

  attr_accessible :billing_street, :billing_zip, :billing_city, :billing_country, :delivery_same, :delivery_street, :delivery_zip, :delivery_city, :delivery_country, :name, :surname, :company_name
  # attr_accessible :title, :body
  has_many :orders, :dependent => :restrict

  after_create :create_token

  validates_presence_of :name, :surname
  
private
  
  def create_token
    self.reset_authentication_token!
  end

public
  
  def full_name
    return self.try(:name) if name.present?
  end

end

app/controllers/customers_controller.rb
class CustomersController < Devise::RegistrationsController

  def create
    build_resource
    resource.password  = resource.password_confirmation = ('0'..'z').to_a.shuffle.first(6).join 

    if resource.save
      if resource.active_for_authentication?
        set_flash_message :notice, :signed_up if is_navigational_format?
        respond_with resource, :location => after_sign_up_path_for(resource)
      else
        set_flash_message :notice, :"signed_up_but_#{resource.inactive_message}" if is_navigational_format?
        expire_session_data_after_sign_in!
        respond_with resource, :location => after_inactive_sign_up_path_for(resource)
      end
    else
      clean_up_passwords resource
      respond_with resource
    end
  end
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/views/customers/_customer_info.html.haml
= f.input :name
= f.input :surname
= f.input :company_name
/ %div.control-group
/   = f.label :name, :class => 'control-label'
/   %div.controls
/     = f.text_field :name 
/ %div.control-group
/   = f.label :surname, :class => 'control-label'
/   %div.controls
/     = f.text_field :surname 
/ %div.control-group
/   = f.label :company_name, :class => 'control-label'
/   %div.controls
/     = f.text_field :company_name 

%hr
= f.input :billing_street
= f.input :billing_zip
= f.input :billing_city
= f.input :billing_country, :as => :string
= f.input :delivery_same, :as => :boolean

%hr
= f.input :delivery_street
= f.input :delivery_zip
= f.input :delivery_city
= f.input :delivery_country, :as => :string

/ %div.control-group
/   = f.label :billing_street, :class => 'control-label'
/   %div.controls 
/     = f.text_field :billing_street 
/ %div.control-group
/   = f.label :billing_zip, :class => 'control-label' 
/   %div.controls 
/     = f.text_field :billing_zip, :maxlength => 5 
/ %div.control-group
/   = f.label :billing_city, :class => 'control-label'
/   %div.controls  
/     = f.text_field :billing_city 
/ %div.control-group
/   = f.label :billing_country, :class => 'control-label'
/   %div.controls 
/     = f.text_field :billing_country 
/ %div.control-group
/   = f.label :delivery_same, :class => 'control-label'
/   %div.controls 
/     = f.check_box :delivery_same 

/ %hr
/ %div.control-group
/   = f.label :delivery_street, :class => 'control-label'
/   %div.controls
/     = f.text_field :delivery_street 
/ %div.control-group
/   = f.label :delivery_zip, :class => 'control-label'
/   %div.controls
/     = f.text_field :delivery_zip, :maxlength => 5 
/ %div.control-group
/   = f.label :delivery_city, :class => 'control-label'
/   %div.controls
/     = f.text_field :delivery_city 
/ %div.control-group
/   = f.label :delivery_country, :class => 'control-label'
/   %div.controls
/     = f.text_field :delivery_country 

app/views/customers/edit.html.erb
<h2>Edit profile</h2>

<%= simple_form_for(resource, :as => resource_name, :url => registration_path(resource_name), :html => { :method => :put }) do |f| %>

    <%= f.input :email %>
<!--   <div data-role="fieldcontain">
    <%= f.label :password %>
    <%= f.password_field :password, :autocomplete => "off" %>
  </div>
  <div data-role="fieldcontain">
    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation %>
  </div>
  <div data-role="fieldcontain">
    <%= f.label :current_password %>
    <%= f.password_field :current_password %>
  </div> -->
    <%= render :partial => 'customer_info', :locals => {:f => f } %>


  <div data-role="fieldcontain">
    <fieldset data-role="controlgroup">
      <legend class= 'ui-input-text'>
        <%= f.submit "Update" %>
      </legend>
      
    </fieldset>
  </div>
<% end %>

<p>Unhappy? <%= link_to "Cancel my account", registration_path(resource_name), :data => { :confirm => "Are you sure?" }, :method => :delete %>.</p>

app/views/customers/index.html.haml
%h1
  List of of Customers
%table.table.table-stripped
  %thead
    %tr
      %th
        id
      %th
        email
      %th
        name
      %th
        company name
      %th
        operations
  %tbody
    - @customers.each do |customer|
      %tr
        %td
          =customer.id
        %td
          =customer.email
        %td
          =customer.name + " " + customer.surname
        %td
          =customer.company_name
        %td
          = link_to "destroy", customer_path(customer), :method => :delete, :confirm => 'Are you sure?', :class => 'btn btn-danger btn-mini'
          = link_to "edit", edit_customer_path(customer), :class => 'btn btn-mini'



/ %ul{"data-role" => "listview", "data-inset" => "true"}
/   - @customers.each do |customer|
/     %li
/       ="Costomer #"
/       = customer.id
/       %br
/       = customer.email
/       %div{"data-role" => "controlgroup", "data-type" => "horizontal"}
/         = link_to "destroy", customer_path(customer), :method => :delete, :data =>{:role => "button"}
/         = link_to "edit", edit_customer_path(customer), :data =>{:role => "button"}

app/views/customers/new.html.erb
<h2>New Customer</h2>

<%= simple_form_for(resource, :as => resource_name, :url => registration_path(resource_name), :html => { :class => 'form-horizontal'}) do |f| %>
  <fieldset>
    <%= f.input :email %>

<!--     <div class="control-group">
      <%= f.label :email, :class => 'control-label' %>
      <div class="controls">
        <%= f.email_field :email %>
      </div>
    </div> -->
<!--   <div data-role="fieldcontain">
    <%= f.label :password %>
    <%= f.password_field :password, :autocomplete => "off" %>
  </div>
  <div data-role="fieldcontain">
    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation %>
  </div> -->

    <%= render :partial => 'customer_info',:locals => {:f => f } %>

    <div class="form-actions">
      <%= f.submit "Create", :class => 'btn btn-primary' %>
    </div>
      
  </fieldset>

<% end %>