config/routes.rb
Hanes::Application.routes.draw do
  root :to => "home#index"  
  devise_for :admins, :controllers => { :registrations => "admins" }
  devise_for :customers, :controllers => { :registrations => "customers" }

  scope "/manage" do
    resources :customers, :controller => :crud_customers do
      resources :orders do
        put :approve, :on => :member
        put :sent, :on => :member
        get :all_orders, :on => :collection
      end
    end
  end

  scope "/manage" do
    resources :admins do
      resources :orders do
        put :approve, :on => :member
        put :sent, :on => :member
        get :all_orders, :on => :collection
        get :to_approve, :on => :collection
      end
    end
  end

  

end

app/models/order.rb
class Order < ActiveRecord::Base
  belongs_to :admin
  belongs_to :customer
  belongs_to :admin_approver, :class_name => 'Admin'
  
  attr_accessible :comment, :delivery_mode, :customer_id, :tracking_number, :admin_approver_id, :send_notification
  attr_accessible :enclosure
  attr_accessor :send_notification

  has_attached_file :enclosure, :path => ":rails_root/public/system/:attachment/:id/:filename",
      :url => "/system/:attachment/:id/:filename"

  before_save :set_admin_if_me_option, :send_notification_to_approver

  validates_presence_of :customer_id, :delivery_mode
  #class metoda
  def self.delivery_modes
    [ "FedEx" ,
      "PPL"     
    ]
  end

  def self.possibly_approvers
    hash = Hash.new
    hash["--customer--"] = -1
    hash["--me--"] = -2
    hash.merge!(Hash[Admin.all.map{|c| [c.email,c.id]}])
    hash
  end

  def approver
    if self.admin_approver_id == -1
      self.customer
    else
      self.admin_approver
    end
  end

protected
  def set_admin_if_me_option
    self.admin_approver = self.admin if self.admin_approver_id == -2 #if me option is selected
  end

  def send_notification_to_approver
    UserMailer.order_to_approve(self).deliver if self.send_notification == "1"
  end


end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  
  before_filter :check_for_resource
  before_filter :authenticate_admin!, :only => [:all_orders,:destroy,:send,:to_approve,:edit]
  before_filter :authenticate_for_approve!, :only => [:approve]

private

  def customer_or_admin_orders_path
    if admin_signed_in?
      admin_orders_path(@user)
    elsif customer_signed_in?
      customer_orders_path(@user)
    else
      root_path
    end
  end
  
  def check_for_resource
    if admin_signed_in?
      @user = current_admin
    elsif customer_signed_in?
      @user = current_customer
    else
      redirect_to root_path
    end 
  end

  def authenticate_for_approve!
    redirect :to => root_path unless admin_signed_in? || customer_signed_in?
  end

public

 def index
    @orders = @user.orders.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @orders }
    end
  end

  # GET /ordes/1
  # GET /ordes/1.json
  def show
    @order = Order.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @order }
    end
  end

  # GET /ordes/new
  # GET /ordes/new.json
  def new
    @order = @user.orders.build

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @order }
    end
  end

  # GET /ordes/1/edit
  def edit
    @order = Order.find(params[:id])
  end

  # POST /ordes
  # POST /ordes.json
  def create
    @order = @user.orders.build(params[:order])
    respond_to do |format|
      if @order.save
        format.html { redirect_to customer_or_admin_orders_path, notice: 'Order was successfully created.' }
        format.json { render json: @order, status: :created, location: @order }
      else
        format.html { render action: "new" }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /ordes/1
  # PUT /ordes/1.json
  def update
    @order = Order.find(params[:id])

    respond_to do |format|
      if @order.update_attributes(params[:order])
        format.html { redirect_to customer_or_admin_orders_path, notice: 'Order was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ordes/1
  # DELETE /ordes/1.json
  def destroy
    authenticate_admin!
    @order = Order.find(params[:id])
    @order.destroy

    respond_to do |format|
      format.html { redirect_to :back, notice: 'Order was deleted.' }
      format.json { head :no_content }
    end
  end

  def approve
    @order = @user.orders.find(params[:id])
    
    respond_to do |format|
      if @order.approver == @user
        @order.approved = true
        if @order.save 
          format.html { redirect_to :back, notice: 'Order was approved.' }
          format.json { render json: @order, status: :created, location: @order }
        else
          format.html { redirect_to :back, notice: 'Order was not approved.' }
          format.json { render json: @order.errors, status: :unprocessable_entity }
        end
      else
        format.html { redirect_to :back, notice: 'You are not eligible to approve' }
      end
    end
  end

  def sent
    #maybe cant send until customer_approved?
    @order = Order.find(params[:id])

    @order.sent = true
    respond_to do |format|
      if @order.save
        UserMailer.order_sent(@order).deliver
        format.html { redirect_to :back, notice: 'Order was marked as sent.' }
        format.json { render json: @order, status: :created, location: @order }
      else
        format.html { redirect_to :back, error: 'Order was not marked as sent.' }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  def all_orders
    @orders = Order.all
    render :index
  end

  def to_approve
    @orders = @user.orders_assigned_for_approval.where(:approved => false)
    render :index
  end

end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/orders/_form.html.haml
= simple_form_for([user, order], {:html => { :class => 'form-horizontal'}}) do |f|
  %fieldset
    = f.input :customer_id, :collection => Hash[Customer.all.map{|c| [c.email,c.id]}], :include_blank => true
    = f.input :delivery_mode, :collection => Order.delivery_modes, :disabled => admin_signed_in? ? false : true, :include_blank => false
    = f.input :tracking_number
    = f.input :comment, input_html: { style: 'height:100px' }
    = f.input :enclosure, :as => :file,:label => "Add file"
    = f.input :admin_approver_id,  :collection => Order.possibly_approvers, :include_blank => true, :disabled => admin_signed_in? ? false : true,:label => 'Approver'
    = f.input :send_notification, :label => 'Send notify to approver',:as => :boolean

    = f.submit :class => 'btn btn-primary'

    / %div.control-group
    /   = f.label :customer_id, :class => 'control-label'
    /   %div.controls
    /     = f.select :customer_id, Hash[Customer.all.map{|c| [c.email,c.id]}], :include_blank => false
    / %div.control-group
    /   = f.label :delivery_mode, :class => 'control-label'
    /   %div.controls
    /     = f.select :delivery_mode, Order.delivery_modes, {} ,:disabled => admin_signed_in? ? false : true
    / %div.control-group
    /   = f.label :tracking_number, :class => 'control-label'
    /   %div.controls
    /     = f.text_field :tracking_number, :disabled => admin_signed_in? ? false : true  
    / %div.control-group
    /   = f.label :comment, :class => 'control-label'
    /   %div.controls
    /     = f.text_area :comment, :style => 'height:100px'
    / %div.control-group
    /   = f.label :enclosure, "Add file", :class => 'control-label'
    /   %div.controls
    /     = f.file_field :enclosure
    / %div.control-group
    /   = f.label :admin_approver_id, :class => 'control-label'
    /   %div.controls
    /     = f.select :admin_approver_id,  Order.possibly_approvers, :include_blank => true, :disabled => admin_signed_in? ? false : true
    / %div.control-group
    /   = f.label :send_notification, "send notification to approver", :class => 'control-label'
    /   %div.controls
    /     = f.check_box :send_notification
    / %div.form-actions
    /   = f.submit :class => 'btn btn-primary'
        

app/views/orders/edit.html.haml
<h2>Edit Order</h2>
= render :partial => 'form', :locals => {:user => @user,:order => @order}

app/views/orders/index.html.haml
%h1
  List of orders
%table.table.table-stripped
  %thead
    %tr
      -if admin_signed_in?
        %th
          Id
      %th
        Customer
      %th
        Created
      %th
        Sent
      %th 
        Approved
  %tbody
    - @orders.each do |order|
      %tr
        -if admin_signed_in?
          %td
            =order.id
        %td
          =order.customer.email
        %td
          =order.created_at.to_date
        %td
          - if order.sent
            %span.label.label-success Sent
          - else
            %span.label.label-warning Not sent

        %td 
          - if order.approved
            %span.label.label-success Approved
          - else
            %span.label.label-warning Not approved


        %td
          -if order.enclosure.present?
            = link_to "Download invoice", order.enclosure.url, :class => 'btn btn-mini'        
          
          - if customer_signed_in?
            
            -if order.approver == current_customer
              = link_to "approve", approve_customer_order_path(current_customer,order), :method => :put, :class => 'btn-mini btn',:confirm => 'Are you sure?' unless order.approved 
          
          - if admin_signed_in?
            = link_to "delete", admin_order_path(current_admin,order), :method => :delete, :confirm => 'Are you sure?', :class => 'btn btn-danger btn-mini'
            = link_to "edit", edit_admin_order_path(current_admin,order), :class => 'btn btn-mini'
            
            - if order.approver == current_admin
              = link_to "approve", approve_admin_order_path(current_admin,order), :method => :put,:class => 'btn btn-mini',:confirm => 'Are you sure?' unless order.approved 
            
            - unless order.sent       
              = link_to "send", sent_admin_order_path(current_admin,order), :method => :put, :confirm => 'Are you sure?', :class => 'btn btn-mini'








/ %ul{"data-role" => "listview", "data-inset" => "true"}
/   - @orders.each do |order|
/     %li
/       ="Order #"
/       =order.id
/       %br
/       ="Created at : "
/       =order.created_at.to_date
/       %br
/       -if order.sent
/         = "sent : yes"
/       - else
/         = "sent : no"
/       %br
/       -if order.approved
/         = "approved : yes"
/       -else
/         = "approved : no"
      
/       %div{"data-role" => "controlgroup", "data-type" => "horizontal"}
        
/         - if customer_signed_in?
/           -if order.approver == current_customer
/             = link_to "approve", approve_customer_order_path(current_customer,order), :method => :put, :data =>{:role => "button" } unless order.approved 
/           = link_to "edit", edit_customer_order_path(current_customer,order), :data =>{:role => "button" }
        

/         - if admin_signed_in?
/           - if order.approver == current_admin
/             = link_to "approve", approve_admin_order_path(current_admin,order), :method => :put,:data =>{:role => "button" } 
/           - unless order.sent       
/             = link_to "send", sent_admin_order_path(current_admin,order), :method => :put, "data-role" => "button"
/             = link_to "destroy", admin_order_path(current_admin,order), :method => :delete, :data =>{:role => "button" }
/           = link_to "edit", edit_admin_order_path(current_admin,order), :data =>{:role => "button" }
          
/         -if order.enclosure.present?
/           = link_to "download file", order.enclosure.url, :data =>{:role => "button" }

app/views/orders/new.html.haml
<h2>New Order</h2>
= render :partial => 'form', :locals => {:user => @user,:order => @order}