config/routes.rb
Hanes::Application.routes.draw do
  root :to => "home#index"  
  devise_for :admins, :controllers => { :registrations => "admins" }
  devise_for :customers, :controllers => { :registrations => "customers" }

  scope "/manage" do
    resources :customers, :controller => :crud_customers do
      resources :orders do
        put :approve, :on => :member
        put :sent, :on => :member
        get :all_orders, :on => :collection
      end
    end
  end

  scope "/manage" do
    resources :admins do
      resources :orders do
        put :approve, :on => :member
        put :sent, :on => :member
        get :all_orders, :on => :collection
        get :to_approve, :on => :collection
      end
    end
  end

  

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Ecozz</title>  
  <%= stylesheet_link_tag "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  

</head>
<body>

  <div class="navbar navbar-fixed-top">
    <div class="navbar-inner">
      <div class="container">
        <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </a>        

        <% if customer_signed_in? -%>

        <div class="nav-collapse">
          <ul class="nav">

          <!-- <%= link_to 'New order', new_customer_order_path(current_customer) %> | -->
          <li><%= link_to 'My orders', customer_orders_path(current_customer) %></li>
          <!-- <%= link_to 'My info', edit_customer_registration_path %> -->
          <li><%= link_to 'Sign out', destroy_customer_session_path, :method => :delete %></li>
          </ul>
        </div>

        <% elsif admin_signed_in? -%>

          <div class="nav-collapse">
            <ul class="nav">

          <li><%= link_to 'New order', new_admin_order_path(current_admin) %></li>
          <li><%= link_to 'New Customer', new_customer_registration_path %></li>
          <li><%= link_to 'New Admin', new_admin_registration_path %></li>
          <li><%= link_to 'Customers', customers_path %></li>
          <li><%= link_to 'All orders', all_orders_admin_orders_path(current_admin) %></li>
          <li><%= link_to 'Orders to approve', to_approve_admin_orders_path(current_admin) %></li>
          <li><%= link_to 'Orders created by me', admin_orders_path(current_admin) %></li>
          <li><%= link_to 'Sign out', destroy_admin_session_path, :method => :delete %></li>

            </ul>
          </div>

        <% else -%>

          <div class="nav-collapse">
            <ul class="nav">

          <li><%= link_to 'Sign in as Admin', new_admin_session_path %></li>

<!--           <%= link_to 'Sign up as Customer', new_customer_registration_path %>
          <%= link_to 'Sign in as Customer', new_customer_session_path %> -->

            </ul>
          </div>

        <% end -%>


      </div>
    </div>
  </div>


  <div class="container">


  <% flash.each do |name, msg| %>
    <div class="alert alert-<%= name == :notice ? "success" : "error" %>">
      <a class="close" data-dismiss="alert">x</a>
      <%= msg  %>
    </div>
  <% end %>

    <div class="row">
      <div class="span12">

        <%= yield %>

      </div>

    </div>
  </div>

</body>
</html>